[tool.black]
line-length = 120
py27 = true
skip-string-normalization = true
include = '(TriblerGUI|Tribler/Core/Modules/MetadataStore)/.*\.pyi?$'

exclude = '''
/(
    \.git
  | \.venv
  | \.idea 
  | snap
  | doc
)/
'''
